repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ".*\\.vscode/"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
        args: ["--lock"]

  # Typo search tool
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.1.1
    hooks:
      - id: cspell

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
    -   id: markdownlint

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: poetry run mypy pytest_qaseio
        language: system
        pass_filenames: false
        types: [ file ]
        stages: [ push ]
