site_name: pytest-qaseio
site_description: Pytest plugin for Qase.io integration
site_url: https://saritasa-nest.github.io/pytest-qaseio/
repo_url: https://github.com/saritasa-nest/pytest-qaseio/
repo_name: pytest-qaseio
theme:
  name: material
  favicon: _static/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.tooltips
extra_css:
  - _static/custom_color.css
plugins:
  - search
  - autorefs
  - mkdocstrings
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.magiclink
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Reference:
      - Api Client: reference/api_client.md
      - Converter: reference/converter.md
      - Debug Info: reference/debug_info.md
      - Hooks: reference/hooks.md
      - Plugin: reference/plugin.md
      - Plugin Exceptions: reference/plugin_exceptions.md
      - Storage: reference/storage.md
  - Changelog: changelog.md
  - Contributing: contributing.md
extra:
  version:
    provider: mike
